spring:
  application:
    name: nnzz
  profiles:
    active: prod

  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: '{카카오 client-id}'
            clientSecret: '{카카오 client-secret}'
            client-authentication-method: post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            ## 서버에서 인증을 마치고 돌아가는 callback uri
            scope:
              - account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


  graphql:
    cors:
      allowed-headers: "*"
      allowed-methods: "*"
      allow-credentials: true
      allowed-origins:
        - https://www.nnzz.today
        - http://localhost:3000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.nnzz.nnzz.dto

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true