spring:
  application:
    name: nnzz
  profiles:
    active: prod
  mvc:
    problemdetails:
      enabled: true #problemDetails 사용설정
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.nnzz.nnzz.dto

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
